all:
	#aclocal
	#autoheader
	#libtoolize --force -c
	#automake -a -f -c
	#autoconf
	autoreconf --install --force
	
clean:
	for d in `find . -name .svn`; \
	do \
	  ( \
	    cd `dirname $$d`; \
	    rm -rf `svn propget svn:ignore .`; \
	  ) \
	done
	  
